main: me.zombie_striker.music.Main
version: ${project.version}
name: Music
api-version: 1.13
softdepend: [CustomItemFramework]
commands:
   music:
      description: Adds extra sounds to your world.
permissions:
   music.*:
     description: Gives access to all Music commands
     children:
       music.admin: true
   music.admin:
     description: Gives access to all Music commands
     children:
       music.changevolumetoglobal: true
       music.default: true
       music.commands: true
   music.default:
     description: Allows users to change the station or volume for a jukebox
     children:
       music.changesong: true
       music.changevolume: true
       music.placejukebox: true
       music.usejukebox: true
author: Zombie_Striker